firstdjango/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from app01.views import home, project, wiki, file, setting, issues, dashboard, statistics

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # home1 为未登录时的主页, home2 为登录或注册过后的主页
    path('pm/home1/', home.home_show1),
    path('image/code/', home.image_code),
    path('pm/home2/', home.home_show2),
    # 价格(支付)
    path('price/', home.price, name='price'),
    path('payment/<int:policy_id>/', home.payment, name='payment'),
    path('pay/', home.pay, name="pay"),
    path('pay/notify/', home.pay_notify, name="pay_notify"),

    # add为注册用户,logout为注销
    path('pm/add/', home.home_add),
    path('logout/', home.home_logout),

    # 类似于脚本对数据库进行处理删除
    path('orm/', home.orm),

    # 项目列表
    path('pm/project/list/', project.project_list, name='project_list'),
    path('pm/project/star/<str:project_type>/<int:project_id>/', project.project_star),
    path('pm/project/unstar/<str:project_type>/<int:project_id>/', project.project_unstar),

    # 项目管理
    path('manage/<int:project_id>/', include([
        path('dashboard/', dashboard.dashboard, name='dashboard'),
        path('dashboard/issues/chart/', dashboard.issues_chart, name='issues_chart'),

        path('statistics/', statistics.statistics, name='statistics'),
        path('statistics/priority/', statistics.statistics_priority, name='statistics_priority'),
        path('statistics/project/user/', statistics.statistics_project_user, name='statistics_project_user'),

        path('wiki/', wiki.wiki, name='wiki'),
        path('wiki/add/', wiki.wiki_add, name='wiki_add'),
        path('wiki/catalog/', wiki.wiki_catalog, name='wiki_catalog'),
        path('wiki/delete/<int:wiki_id>/', wiki.wiki_delete, name='wiki_delete'),
        path('wiki/edit/<int:wiki_id>/', wiki.wiki_edit, name='wiki_edit'),
        path('wiki/upload/', wiki.wiki_upload, name='wiki_upload'),

        path('file/', file.file, name='file'),
        path('file/delete/', file.file_delete, name='file_delete'),
        path('file/post/', file.file_post, name='file_post'),
        path('file/download/<int:file_id>/', file.file_download, name='file_download'),
        path('cos/credential/', file.cos_credential, name='cos_credential'),

        path('setting/', setting.setting, name='setting'),
        path('setting/delete/', setting.delete, name='setting_delete'),

        path('issues/', issues.issues, name='issues'),
        path('issues/detail/<int:issues_id>/', issues.issues_detail, name='issues_detail'),
        path('issues/record/<int:issues_id>/', issues.issues_record, name='issues_record'),
        path('issues/change/<int:issues_id>/', issues.issues_change, name='issues_change'),
        path('issues/invite/url/', issues.invite_url, name='invite_url'),
    ])),
    path('invite/join/<str:code>/', issues.invite_join, name='invite_join'),
]

app01/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    name = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    email = models.EmailField(verbose_name="邮箱", max_length=32)
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)
    img = models.FileField(verbose_name="头像", max_length=128, null=True, blank=True, upload_to='user/')

    def __str__(self):
        return self.name


class PricePolicy(models.Model):
    """ 价格策略 """
    category_choices = (
        (1, '免费版'),
        (2, '收费版'),
        (3, '其他'),
    )
    category = models.SmallIntegerField(verbose_name="收费类型", default=2, choices=category_choices)
    title = models.CharField(verbose_name="标题", max_length=32)
    price = models.PositiveIntegerField(verbose_name="价格")

    project_num = models.PositiveIntegerField(verbose_name="项目数")
    project_member = models.PositiveIntegerField(verbose_name="项目成员个数")
    project_space = models.PositiveIntegerField(verbose_name="单项目空间", help_text='G')
    project_size = models.PositiveIntegerField(verbose_name="单项目大小", help_text='M')

    create_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)


class Transaction(models.Model):
    """ 交易记录 """
    status_choice = (
        (1, '未支付'),
        (2, '已支付'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choice)
    order = models.CharField(verbose_name='订单号', max_length=64, unique=True)
    user = models.ForeignKey(verbose_name='用户', to='User', on_delete=models.CASCADE)
    price_policy = models.ForeignKey(verbose_name='价格策略', to=PricePolicy, on_delete=models.CASCADE)
    count = models.IntegerField(verbose_name='数量', help_text='0表示无限期')
    price = models.IntegerField(verbose_name='实际支付价格')
    start_datetime = models.DateTimeField(verbose_name='开始时间', null=True, blank=True)
    end_datetime = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Project(models.Model):
    """ 项目表 """
    COLOR_CHOICES = (
        (1, '#56b8eb'),
        (2, '#f28033'),
        (3, '#ebc656'),
        (4, '#a2d148'),
        (5, '#20BFA4'),
        (6, '#7461c2'),
        (7, '#20bfa3'),
    )
    name = models.CharField(verbose_name='项目名', max_length=32)
    color = models.SmallIntegerField(verbose_name='颜色', choices=COLOR_CHOICES, default=1)
    desc = models.CharField(verbose_name='项目描述', max_length=255, null=True, blank=True)
    use_space = models.IntegerField(verbose_name='项目已使用空间', default=0)
    star = models.BooleanField(verbose_name='星标', default=False)
    join_count = models.SmallIntegerField(verbose_name='参与人数', default=1)
    creator = models.ForeignKey(verbose_name='创建者', to='User', on_delete=models.CASCADE)
    creator_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    bucket = models.CharField(verbose_name="cos桶", max_length=128)
    region = models.CharField(verbose_name="cos区域", max_length=32)


class ProjectUser(models.Model):
    """ 项目参与者 """
    user = models.ForeignKey(verbose_name='用户', to='User', on_delete=models.CASCADE)
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    star = models.BooleanField(verbose_name='星标', default=False)
    create_datetime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)


class Wiki(models.Model):
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='标题', max_length=32)
    content = models.TextField(verbose_name='内容')
    parent = models.ForeignKey(verbose_name='父文章', to='Wiki', null=True, blank=True, on_delete=models.CASCADE,
                               related_name='children')
    depth = models.IntegerField(verbose_name="深度", default=1)

    def __str__(self):
        return self.title


class FileRepository(models.Model):
    """ 文件库 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    file_type_choices = (
        (1, '文件'),
        (2, '文件夹')
    )
    file_type = models.SmallIntegerField(verbose_name='类型', choices=file_type_choices)
    name = models.CharField(verbose_name='文件夹名称', max_length=32, help_text="文件/文件夹名")
    key = models.CharField(verbose_name='文件存储在COS中的key', max_length=128, null=True, blank=True)
    file_size = models.IntegerField(verbose_name='文件大小', null=True, blank=True)
    file_path = models.CharField(verbose_name='文件路径', max_length=255, null=True, blank=True)
    parent = models.ForeignKey(verbose_name='父级目录', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.CASCADE)
    update_user = models.ForeignKey(verbose_name='最近更新者', to='User', on_delete=models.CASCADE)
    update_datetime = models.DateTimeField(verbose_name='更新时间', auto_now=True)


class Issues(models.Model):
    """ 问题 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    issues_type = models.ForeignKey(verbose_name='问题类型', to='IssuesType', on_delete=models.CASCADE)
    module = models.ForeignKey(verbose_name='模块', to='Module', null=True, blank=True, on_delete=models.CASCADE)

    subject = models.CharField(verbose_name='主题', max_length=80)
    desc = models.TextField(verbose_name='问题描述')
    priority_choices = (
        ('danger', '高'),
        ('warning', '中'),
        ('success', '低'),
    )
    priority = models.CharField(verbose_name='优先级', max_length=12, choices=priority_choices, default='danger')

    status_choices = (
        (1, '新建'),
        (2, '处理中'),
        (3, '已解决'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)
    assign = models.ForeignKey(verbose_name='指派', to='User', related_name='task', null=True, blank=True,
                               on_delete=models.CASCADE)
    attention = models.ManyToManyField(verbose_name='关注者', to='User', related_name='observe', blank=True)
    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)
    mode_choices = (
        (1, '公开模式'),
        (2, '隐私模式')
    )
    mode = models.SmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)

    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.CASCADE)
    creator = models.ForeignKey(verbose_name='创建者', to='User', related_name='create_problems',
                                on_delete=models.CASCADE)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='最后更新时间', auto_now=True)

    def __str__(self):
        return self.subject


class Module(models.Model):
    """ 模块 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='模块名称', max_length=32)

    def __str__(self):
        return self.title


class IssuesType(models.Model):
    """ 问题类型 """
    PROJECT_INIT_LIST = ['任务', '功能', 'Bug']

    title = models.CharField(verbose_name='类型名称', max_length=32)
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class IssuesReply(models.Model):
    """ 问题回复"""

    reply_type_choices = (
        (1, '修改记录'),
        (2, '回复')
    )
    reply_type = models.IntegerField(verbose_name='类型', choices=reply_type_choices)

    issues = models.ForeignKey(verbose_name='问题', to='Issues', on_delete=models.CASCADE)
    content = models.TextField(verbose_name='描述')
    creator = models.ForeignKey(verbose_name='创建者', to='User', related_name='create_reply', on_delete=models.CASCADE)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复', to='self', null=True, blank=True, on_delete=models.CASCADE)


class ProjectInvite(models.Model):
    """ 项目邀请码 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    code = models.CharField(verbose_name='邀请码', max_length=64, unique=True)
    count = models.PositiveIntegerField(verbose_name='限制数量', null=True, blank=True, help_text='空表示无数量限制')
    use_count = models.PositiveIntegerField(verbose_name='已邀请数量', default=0)
    period_choices = (
        (30, '30分钟'),
        (60, '1小时'),
        (300, '5小时'),
        (1440, '24小时'),
    )
    period = models.IntegerField(verbose_name='有效期', choices=period_choices, default=1440)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    creator = models.ForeignKey(verbose_name='创建者', to='User', related_name='create_invite',
                                on_delete=models.CASCADE)

app01/forms/widgets.py
from django.forms import RadioSelect


class ColorRadioSelect(RadioSelect):
    """ 自定义ModelForm关于颜色的选项插件 """
    template_name = "widgets/color_radio/radio.html"
    option_template_name = "widgets/color_radio/radio_option.html"

app01/views/dashboard.py
import datetime
import time
import collections
from django.shortcuts import render
from django.db.models import Count
from django.http import JsonResponse
from app01 import models


def dashboard(request, project_id):
    """ 问题概览 """
    # 问题处理
    status_dict = {}
    for key, text in models.Issues.status_choices:
        status_dict[key] = {"text": text, "count": 0}
    issues_data = models.Issues.objects.filter(project_id=project_id).values('status').annotate(ct=Count('id'))
    for item in issues_data:
        status_dict[item['status']]['count'] = item['ct']

    # 成员处理
    user_list = models.ProjectUser.objects.filter(project_id=project_id).values_list('user_id', 'user__name')

    # 发表问题处理
    top_ten = models.Issues.objects.filter(project_id=project_id, assign__isnull=False).order_by('-id')[0:10]

    context = {
        'status_dict': status_dict,
        'user_list': user_list,
        'top_ten_object': top_ten,
    }

    return render(request, 'dashboard.html', context)


def issues_chart(request, project_id):
    """ 生成highcharts数据 """

    # 最近30天每天创建的问题数量
    today = datetime.datetime.now().date()
    date_dict = collections.OrderedDict()
    for i in range(0, 30):
        date = today - datetime.timedelta(days=i)
        date_dict[date.strftime("%Y-%m-%d")] = [time.mktime(date.timetuple()) * 1000, 0]
    # result = models.Issues.objects.filter(project_id=project_id,
    #                                       create_datetime__gte=today - datetime.timedelta(days=30)).extra(
    #     select={'ctime': "strftime('%%Y-%%m-%%d',app01_issues.create_datetime)"}).values('ctime').annotate(
    #     ct=Count('id'))

    for item in models.Issues.objects.filter(project_id=project_id,
                                             create_datetime__gte=today - datetime.timedelta(days=30))\
            .values_list('create_datetime'):
        each_date = item[0].strftime("%Y-%m-%d")
        date_dict[each_date][1] += 1

    return JsonResponse({'status': True, 'data': list(date_dict.values())})

app01/views/project.py
import time
from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse
from app01.forms.project import ProjectModelForm
from app01.utils.cos import create_bucket
from app01 import models


def project_list(request):
    # 项目总览
    if request.method == 'GET':
        project_dict = {'star': [], 'my': [], 'join': []}
        my_project_list = models.Project.objects.filter(creator=request.tracer.user)
        for row in my_project_list:
            if row.star:
                project_dict['star'].append({"value": row, 'type': 'my'})
            else:
                project_dict['my'].append(row)
        join_project_list = models.ProjectUser.objects.filter(user=request.tracer.user)
        for row in join_project_list:
            if row.star:
                project_dict['star'].append({"value": row.project, 'type': 'join'})
            else:
                project_dict['join'].append(row.project)

        form = ProjectModelForm(request)
        return render(request, 'project_list.html', {'form': form, 'project_dict': project_dict})
    form = ProjectModelForm(request, data=request.POST)
    if form.is_valid():
        # 创建COS桶
        bucket = "{}{}-1317188553".format(request.tracer.user.mobile,
                                          str(time.strftime('%Y%m%d%H%M%S', time.localtime(time.time()))))
        region = "ap-nanjing"
        create_bucket(bucket, region)

        form.instance.bucket = bucket
        form.instance.region = region
        form.instance.creator = request.tracer.user
        instance = form.save()
        # 项目初始化问题类型
        issues_type_object_list = []
        for item in models.IssuesType.PROJECT_INIT_LIST:
            issues_type_object_list.append(models.IssuesType(project=instance, title=item))
        models.IssuesType.objects.bulk_create(issues_type_object_list)
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})


def project_star(request, project_type, project_id):
    # 收藏项目
    if project_type == 'my':
        models.Project.objects.filter(id=project_id, creator=request.tracer.user).update(star=True)
        return redirect('/pm/project/list/')
    if project_type == 'join':
        models.ProjectUser.objects.filter(project_id=project_id, user=request.tracer.user).update(star=True)
        return redirect('/pm/project/list/')

    return HttpResponse("错误")


def project_unstar(request, project_type, project_id):
    # 取消收藏项目
    if project_type == 'my':
        models.Project.objects.filter(id=project_id, creator=request.tracer.user).update(star=False)
        return redirect('/pm/project/list/')
    if project_type == 'join':
        models.ProjectUser.objects.filter(project_id=project_id, user=request.tracer.user).update(star=False)
        return redirect('/pm/project/list/')

    return HttpResponse("错误")

app01/templates/home_log_in.html
{% extends 'layout/basic.html' %}
{% block title %}首页{% endblock %}

{% block login %}

    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
           aria-expanded="false">{{ request.session.info.name }}<span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="/pm/project/list/">管理中心</a></li>
            <li><a href="#">更多信息</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/logout/">注销</a></li>
        </ul>
    </li>

{% endblock %}

app01/templates/home_not_log_in.html
{% extends 'layout/basic.html' %}
{% block title %}首页{% endblock %}
{% block css %}

    <style>
        .lg {
            border: none;
            background: none;
        }
    </style>

{% endblock %}


{% block login %}
    <li>
        <a>
            <button id="sign_in" class="lg">登录</button>
        </a>
    </li>
    <li>
        {#        <button href="pm/add/" id="sign_up" class="lg">注册</button>#}
        <a href="/pm/add/" id="sign_up">注册</a>
    </li>
{% endblock %}

{% block content %}

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">登录</h4>
                </div>
                <div class="modal-body">
                    <form method="post" novalidate id="formAdd">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>邮箱或手机号</label>
                            {{ form.mobile }}
                            <span style="color: #b92c28">{{ form.mobile.errors.0 }}</span>
                        </div>
                        <div class="form-group">
                            <label>密码</label>
                            {{ form.password }}
                            <span style="color: #b92c28">{{ form.password.errors.0 }}</span>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Check me out
                            </label>
                        </div>

                        <div class="form-group">
                            <label for="id_code">图片验证码</label>
                            <div class="row">
                                <div class="col-xs-7">
                                    {{ form.code }}
                                    <span style="color: #b92c28">{{ form.code.errors.0 }}</span>
                                </div>
                                <div class="col-xs-5">
                                    <img id="image_code" src="/image/code/" style="width: 125px" title="点击更换">
                                </div>
                            </div>
                        </div>
                        <button id="btnSave" type="submit" class="btn btn-primary">登录</button>
                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock %}


{% block js %}

    <script type="text/javascript">
        $(function () {
            bindBtnClinkinEvent();
            bindBtnSigninEvent();
            bindImgClinkinEvent();
        })

        function bindBtnClinkinEvent() {
            {# 显示登录对话框 #}
            $("#sign_in").click(function () {
                $("#formAdd")[0].reset();
                $("#myModal").modal("show");
            });
        }

        function bindBtnSigninEvent() {

            {#$("#btnSave").click(function () {#}
            {#    $(".error-msg").empty();#}
            {##}
            {#    $.ajax({#}
            {#        url: "/pm/home1/",#}
            {#        type: "post",#}
            {#        data: $("#formAdd").serialize(),#}
            {#        success: function (res){#}
            {#            if(res.status) alert("创建成功");#}
            {#            else{#}
            {#                alert("创建失败");#}
            {#                $.each(res.error, function (name, errorList){#}
            {#                    $(".error-msg").next().text(errorList[0]);#}
            {#                })#}
            {#            }#}
            {#        }#}
            {#    })#}
        }

        function bindImgClinkinEvent() {
            {# 刷新图片验证码 #}
            $('#image_code').click(function () {
                var old_src = $(this).attr('src')
                $(this).attr('src', old_src + "?");
            })
        }
    </script>

{% endblock %}

app01/templates/project_list.html
{% extends 'layout/manage.html' %}
{% load static %}

{% block title %}
    项目管理
{% endblock %}

{% block css %}
    <style>
        .c1 {
            margin-top: 20px;
        }

        .panel-body {
            padding: 0;
            display: flex;
            flex-direction: row;
            justify-content: left;
            align-items: flex-start;
            flex-wrap: wrap;
        }

        .panel-body > .item {
            border-radius: 6px;
            width: 228px;
            border: 1px solid #dddddd;
            margin: 20px 10px;
        }

        .panel-body > .item:hover {
            border: 1px solid #f0ad4e;
        }

        .panel-body > .item > .title {
            height: 104px;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
            font-size: 15px;
            text-decoration: none;
        }

        .panel-body > .item > .info {
            padding: 10px 10px;
            display: flex;
            justify-content: space-between;
            border-bottom-left-radius: 6px;
            border-top-right-radius: 6px;
            color: #8c8c8c;
        }

        .panel-body > .item > .info a {
            text-decoration: none;
        }

        .panel-body > .item > .info .fa-star {
            font-size: 18px;
        }

        .color_radio label {
            margin-left: 0;
            padding-left: 0;
        }

        .color-radio input[type="radio"] {
            display: none;
        }

        .color-radio input[type="radio"] + .cycle {
            display: inline-block;
            height: 25px;
            width: 25px;
            border-radius: 50%;
            border: 2px solid #dddddd;
        }

        .color-radio input[type="radio"]:checked + .cycle {
            border: 2px solid black;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid c1">
        {#  新建项目  #}
        <a class="btn btn-default" style="color: black" data-toggle="modal" data-target="#addModal">
            <i class="fa fa-plus-square" aria-hidden="true"></i>
            新建项目</a>

        {#  项目显示面板  #}
        <div class="panel panel-default c1">
            <div class="panel-heading"><i class="fa fa-star" aria-hidden="true"></i>收藏</div>
            <div class="panel-body">
                {% for item in project_dict.star %}
                    <div class="item">
                        <a href="{% url 'dashboard' project_id=item.value.id %}" class="title"
                           style="background-color: {{ item.value.get_color_display }};">{{ item.value.name }}</a>
                        <div class="info">
                            <div>
                                <a href="/pm/project/unstar/{{ item.type }}/{{ item.value.id }}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #f0ad4e"></i>
                                </a>
                                <span>{{ item.value.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.value.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-cubes" aria-hidden="true"></i>我创建的</div>
            <div class="panel-body">
                {% for item in project_dict.my %}
                    <div class="item">
                        <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="/pm/project/star/{{ 'my' }}/{{ item.id }}">
                                    <i class="fa fa-star" aria-hidden="true" style="color:#d5d5d5;"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-handshake-o" aria-hidden="true"></i>我参与的</div>
            <div class="panel-body">
                {% for item in project_dict.join %}
                    <div class="item">
                        <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="/pm/project/star/{{ 'join' }}/{{ item.id }}">
                                    <i class="fa fa-star" aria-hidden="true" style="color:#d5d5d5;"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


    {#  新建项目弹窗  #}
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <div class="modal-body">
                    <form id="addForm">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <span class="error-msg" style="color: red; font-size: 13px; position: absolute"></span>
                            </div>
                        {% endfor %}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id='btnSubmit' type="button" class="btn btn-primary">确定</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}

    <script>
        $(function () {
            bindSubmit();
        });

        function bindSubmit() {
            $('#btnSubmit').click(function () {
                $.ajax({
                    url: "/pm/project/list/",
                    type: "POST",
                    data: $('#addForm').serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            {#  刷新页面 location.reload() #}
                            location.href = location.href
                        } else {
                            $.each(res.error, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }
    </script>

{% endblock %}